# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react_native_navigation_bootstrap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react_native_navigation_bootstrap
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

end
